// do not edit this file, use buildOptions.js
export const options = {
    "0_introduction": [
        "1_introduction.js",
        "2_random_walker.js",
        "3_gaussian_distribution.js",
        "4_custom_distribution.js",
        "5_perlin_noise.js"
    ],
    "1_vectors": [
        "1_bouncing_ball.js",
        "2_mouse_acceleration.js",
        "3_mouse_string.js"
    ],
    "2_forces": [
        "1_mover.js"
    ]
};