// do not edit this file, use buildOptions.js
export const options = {
    "0_introduction": [
        "1_introduction.js",
        "2_random_walker.js",
        "3_gaussian_distribution.js",
        "4_custom_distribution.js",
        "5_perlin_noise.js"
    ],
    "1_vectors": [
        "1_bouncing_ball.js",
        "2_mouse_acceleration.js",
        "3_mouse_string.js"
    ],
    "2_forces": [
        "1_mover.js",
        "2_mover_mass.js",
        "3_mover_friction.js",
        "4_fluid_drag.js",
        "5_gravitational_attraction.js"
    ],
    "3_oscillation": [
        "1_rotation.js",
        "2_polar_coordinates.js",
        "3_simple_harmonic_motion.js",
        "4_oscillators.js",
        "5_sin_wave.js",
        "6_gravitational_pullers.js",
        "7_pendulum.js",
        "8_springs.js",
        "9_trampoline.js"
    ],
    "4_particle_systems": [
        "1_particles.js",
        "2_particles_wind.js",
        "3_fire.js"
    ],
    "5_physics_engines": [
        "1_getting_started.js",
        "2_random_polygons.js",
        "3_random_car.js",
        "4_introduction.js",
        "5_circles.js",
        "6_constraints.js"
    ],
    "6_autonomous_agents": [
        "1_seek.js",
        "2_arrive.js",
        "3_flow_field.js",
        "4_angle_between.js",
        "5_scalar_projection.js",
        "6_path_following.js",
        "7_complex_path_following.js",
        "8_group_alignment.js",
        "9_group_separation.js",
        "10_seek_separate.js",
        "11_path_separate.js",
        "12_flocking.js"
    ],
    "7_cellular_automata": [
        "1_single_grid.js",
        "2_game_of_life.js",
        "3_hex_game_of_life.js"
    ],
    "8_fractals": [
        "1_recursive_circles.js",
        "2_sierpinski_triangle.js",
        "3_cantor_set.js"
    ],
    "11_creative_coding": [
        "1_iterative_squares.js",
        "2_face_generator.js",
        "3_circle_clock.js",
        "3_circle_clock_matter.js"
    ],
    "12_random": [
        "1_fractal_tree.js",
        "2_grid_dynamic_sketches.js"
    ]
};