const fs = require("fs");
const path = require("path");

/**
 * generate options.js file so it can be referenced on the frontend
 * @param {string} chaptersDir - where to read chapters from
 * @param {string} buildDir - where to put output file
 */
const buildOptions = (chaptersDir = "./chapters", buildDir = "./js") => {
    const chapters = fs.readdirSync(chaptersDir);
    const options = {};

    for (const chapter of chapters) {
        const demos = fs.readdirSync(path.join(chaptersDir, chapter));
        options[chapter] = demos.filter((demo) => demo.endsWith(".js"));
    }

    fs.writeFileSync(
        path.join(buildDir, "options.js"),
        `// do not edit this file, use buildOptions.js
export const options = ${JSON.stringify(options, null, 4)};`
    );
};

buildOptions();
